# Generated by Django 5.0.3 on 2024-04-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="books",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.author"
            ),
        ),
    ]
